name: Build IPA

on:
  workflow_dispatch:           # manueller Start-Button

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    # 1️⃣ Code aus dem Repo holen
    - name: Checkout
      uses: actions/checkout@v3

    # 2️⃣ Python bereitstellen
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 3️⃣ System- und Pip-Abhängigkeiten
    - name: Install deps
      run: |
        brew install autoconf automake libtool pkg-config
        pip install --upgrade pip cython buildozer
        pip install pbxproj

    # 4️⃣ Buildozer ausführen
    - name: Build IPA
      run: buildozer ios debug

    # 5️⃣ IPA als Artefakt hochladen
    - name: Upload IPA
      uses: actions/upload-artifact@v4       # ← gleiche Einrückung!
      with:
        name: vintedtracker-ipa
        path: bin/*.ipa
