name: Build IPA

on:
  workflow_dispatch:           # Startet per Button

jobs:
  build-ios:
    runs-on: macos-latest      # GitHub-gehosteter macOS-Runner

    steps:
    # 1️⃣ Code aus dem Repo holen
    - name: Checkout
      uses: actions/checkout@v3

    # 2️⃣ Passende Python-Version bereitstellen
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 3️⃣ System- und Python-Abhängigkeiten installieren
    - name: Install deps
      run: |
        brew install autoconf automake libtool pkg-config
        pip install --upgrade pip cython buildozer

    # 4️⃣ Buildozer ausführen, um die .ipa zu erzeugen
    - name: Build IPA
      run: buildozer ios debug

    # 5️⃣ Fertige IPA als Artefakt hochladen
    - name: Upload IPA
      uses: actions/upload-artifact@v2    # ← v2 statt v3
      with:
        name: vintedtracker-ipa
        path: bin/*.ipa
