name: Build IPA
on: workflow_dispatch

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install deps
      run: |
        brew install autoconf automake libtool pkg-config readline
        pip install --upgrade pip
        pip install "Cython==0.29.36"
        pip install buildozer
        pip install "pbxproj<4"

    - name: Build IPA
      run: buildozer ios debug

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: vintedtracker-ipa
        path: bin/*.ipa
